sudo: false
language: cpp
notifications:
  irc: "irc.freenode.net#orange-lang"
compiler:
  - clang
  - gcc
cache: apt
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - kubuntu-backports
    - llvm-toolchain-precise-3.6
    packages:
    - llvm-3.6
    - llvm-3.6-dev
    - libedit-dev
    - g++-4.9
    - cmake
    - clang-3.6
matrix:
  include:
    - os: osx
      compiler: clang
      before_install:
        - brew update
        - brew install llvm
        - export CMAKE_LLVM_PATH=-DLLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake
git:
  submodules: false
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_LLVM_PATH -DCMAKE_BUILD_TYPE=Debug
  - make all
  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
