sudo: false
language: cpp
notifications:
  irc:
    channels:
      - "irc.freenode.net#orange-lang"
    on_success: change
    on_failure: change
  email: false
compiler:
  - clang
  - gcc
cache: apt
os: linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kubuntu-backports
    packages:
    - libedit-dev
    - g++-4.9
    - clang
matrix:
  include:
    - os: osx
      compiler: clang
      before_install:
        - git submodule init
        - git submodule update
        - brew update
        - brew upgrade cmake
git:
  submodules: false
before_install:
  - git submodule init
  - git submodule update
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # Snag a newer version of CMake on linux
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      ls ${DEPS_DIR}/cmake/bin
      which cmake
      cmake --version
    fi

  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
script:
  # Make sure we go back to the original build directory
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make all
  - ctest -V
